dsn: "cockroach://root@localhost:26257/hydra?sslmode=disable&max_conns=20&max_idle_conns=4"
strategies:
  access_token: jwt
  scope: exact

ttl:
  access_token: 24h
  refresh_token: 1h
  id_token: 1h
  auth_code: 1h
  login_consent_request: 1h

magnolia:
  address: api.cornflower.fuxi.is
  insecure_port: 50551
  secure_port: 50552

secrets:
  cookie:
    - this-is-the-primary-secret
    - this-is-an-old-secret
    - this-is-another-old-secret
  system:
    - this-is-the-primary-secret
    - this-is-an-old-secret
    - this-is-another-old-secret
