// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// List available namespaces before user registration
	AvailableNamespace(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*NamespacesResponse, error)
	// User registration
	ApplyRegistrationCode(ctx context.Context, in *ApplyRegistrationCodeRequest, opts ...grpc.CallOption) (*ApplyRegistrationCodeResponse, error)
	Register(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error)
	Authenticate(ctx context.Context, in *UserAuthenticationRequest, opts ...grpc.CallOption) (*UserAuthenticationResponse, error)
	Unregister(ctx context.Context, in *UserUnregisterRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// License management
	ListLicense(ctx context.Context, in *LicenseManagementRequest, opts ...grpc.CallOption) (*LicensesResponse, error)
	CreateLicense(ctx context.Context, in *LicenseManagementRequest, opts ...grpc.CallOption) (*LicenseResponse, error)
	RevokeLicense(ctx context.Context, in *RevokeLicenseRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) AvailableNamespace(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*NamespacesResponse, error) {
	out := new(NamespacesResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/AvailableNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ApplyRegistrationCode(ctx context.Context, in *ApplyRegistrationCodeRequest, opts ...grpc.CallOption) (*ApplyRegistrationCodeResponse, error) {
	out := new(ApplyRegistrationCodeResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/ApplyRegistrationCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Register(ctx context.Context, in *UserRegistrationRequest, opts ...grpc.CallOption) (*UserRegistrationResponse, error) {
	out := new(UserRegistrationResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Authenticate(ctx context.Context, in *UserAuthenticationRequest, opts ...grpc.CallOption) (*UserAuthenticationResponse, error) {
	out := new(UserAuthenticationResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Unregister(ctx context.Context, in *UserUnregisterRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/Unregister", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ListLicense(ctx context.Context, in *LicenseManagementRequest, opts ...grpc.CallOption) (*LicensesResponse, error) {
	out := new(LicensesResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/ListLicense", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateLicense(ctx context.Context, in *LicenseManagementRequest, opts ...grpc.CallOption) (*LicenseResponse, error) {
	out := new(LicenseResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/CreateLicense", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RevokeLicense(ctx context.Context, in *RevokeLicenseRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.UserService/RevokeLicense", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// List available namespaces before user registration
	AvailableNamespace(context.Context, *GeneralPaginationRequest) (*NamespacesResponse, error)
	// User registration
	ApplyRegistrationCode(context.Context, *ApplyRegistrationCodeRequest) (*ApplyRegistrationCodeResponse, error)
	Register(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error)
	Authenticate(context.Context, *UserAuthenticationRequest) (*UserAuthenticationResponse, error)
	Unregister(context.Context, *UserUnregisterRequest) (*GeneralResponse, error)
	// License management
	ListLicense(context.Context, *LicenseManagementRequest) (*LicensesResponse, error)
	CreateLicense(context.Context, *LicenseManagementRequest) (*LicenseResponse, error)
	RevokeLicense(context.Context, *RevokeLicenseRequest) (*GeneralResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) AvailableNamespace(context.Context, *GeneralPaginationRequest) (*NamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableNamespace not implemented")
}
func (UnimplementedUserServiceServer) ApplyRegistrationCode(context.Context, *ApplyRegistrationCodeRequest) (*ApplyRegistrationCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApplyRegistrationCode not implemented")
}
func (UnimplementedUserServiceServer) Register(context.Context, *UserRegistrationRequest) (*UserRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServiceServer) Authenticate(context.Context, *UserAuthenticationRequest) (*UserAuthenticationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedUserServiceServer) Unregister(context.Context, *UserUnregisterRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unregister not implemented")
}
func (UnimplementedUserServiceServer) ListLicense(context.Context, *LicenseManagementRequest) (*LicensesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLicense not implemented")
}
func (UnimplementedUserServiceServer) CreateLicense(context.Context, *LicenseManagementRequest) (*LicenseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLicense not implemented")
}
func (UnimplementedUserServiceServer) RevokeLicense(context.Context, *RevokeLicenseRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeLicense not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_AvailableNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AvailableNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/AvailableNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AvailableNamespace(ctx, req.(*GeneralPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ApplyRegistrationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRegistrationCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ApplyRegistrationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/ApplyRegistrationCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ApplyRegistrationCode(ctx, req.(*ApplyRegistrationCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*UserRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserAuthenticationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Authenticate(ctx, req.(*UserAuthenticationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Unregister_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserUnregisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Unregister(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/Unregister",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Unregister(ctx, req.(*UserUnregisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ListLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseManagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/ListLicense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListLicense(ctx, req.(*LicenseManagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseManagementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/CreateLicense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateLicense(ctx, req.(*LicenseManagementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RevokeLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeLicenseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RevokeLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.UserService/RevokeLicense",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RevokeLicense(ctx, req.(*RevokeLicenseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableNamespace",
			Handler:    _UserService_AvailableNamespace_Handler,
		},
		{
			MethodName: "ApplyRegistrationCode",
			Handler:    _UserService_ApplyRegistrationCode_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _UserService_Authenticate_Handler,
		},
		{
			MethodName: "Unregister",
			Handler:    _UserService_Unregister_Handler,
		},
		{
			MethodName: "ListLicense",
			Handler:    _UserService_ListLicense_Handler,
		},
		{
			MethodName: "CreateLicense",
			Handler:    _UserService_CreateLicense_Handler,
		},
		{
			MethodName: "RevokeLicense",
			Handler:    _UserService_RevokeLicense_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magnolia.proto",
}

// EntropyServiceClient is the client API for EntropyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EntropyServiceClient interface {
	// For TLD, when we using HLF, it seems like the channel in HLF.
	AvailableNamespace(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*NamespacesResponse, error)
	CurrentNamespace(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*NamespaceResponse, error)
	ActivateNamespace(ctx context.Context, in *NamespaceRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	// For Domain
	CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	DeleteDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error)
	ListDomain(ctx context.Context, in *ListDomainRequest, opts ...grpc.CallOption) (*DomainsResponse, error)
	// For DNS RR
	AddDomainResourceRecord(ctx context.Context, in *CreateDomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordResponse, error)
	UpdateDomainResourceRecord(ctx context.Context, in *UpdateDomainResourceRecordRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	DeleteDomainResourceRecord(ctx context.Context, in *DomainResourceRecordRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetDomainResourceRecord(ctx context.Context, in *DomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordResponse, error)
	FindDomainResourceRecord(ctx context.Context, in *FindDomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordsResponse, error)
	// For Identifier
	CreateIdentityIdentifier(ctx context.Context, in *CreateIdentityIdentifierRequest, opts ...grpc.CallOption) (*IdentityIdentifierResponse, error)
	DeleteIdentityIdentifier(ctx context.Context, in *IdentityIdentifierRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetIdentityIdentifier(ctx context.Context, in *IdentityIdentifierRequest, opts ...grpc.CallOption) (*IdentityIdentifierResponse, error)
	// For Data Identifier
	CreateDataIdentifier(ctx context.Context, in *CreateDataIdentifierRequest, opts ...grpc.CallOption) (*DataIdentifierResponse, error)
	DeleteDataIdentifier(ctx context.Context, in *DataIdentifierRequest, opts ...grpc.CallOption) (*GeneralResponse, error)
	GetDataIdentifier(ctx context.Context, in *DataIdentifierRequest, opts ...grpc.CallOption) (*DataIdentifierResponse, error)
	GetDataIdentifiers(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error)
	FindDataIdentifierByOwner(ctx context.Context, in *FindDataIdentifierByOwnerRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error)
	FindDataIdentifierByMetadata(ctx context.Context, in *FindDataIdentifierByMetadataRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error)
	FindDataIdentifierByTag(ctx context.Context, in *FindDataIdentifierByTagRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error)
}

type entropyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEntropyServiceClient(cc grpc.ClientConnInterface) EntropyServiceClient {
	return &entropyServiceClient{cc}
}

func (c *entropyServiceClient) AvailableNamespace(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*NamespacesResponse, error) {
	out := new(NamespacesResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/AvailableNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) CurrentNamespace(ctx context.Context, in *GeneralRequest, opts ...grpc.CallOption) (*NamespaceResponse, error) {
	out := new(NamespaceResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/CurrentNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) ActivateNamespace(ctx context.Context, in *NamespaceRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/ActivateNamespace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) CreateDomain(ctx context.Context, in *CreateDomainRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/CreateDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) DeleteDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/DeleteDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) GetDomain(ctx context.Context, in *DomainRequest, opts ...grpc.CallOption) (*DomainResponse, error) {
	out := new(DomainResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/GetDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) ListDomain(ctx context.Context, in *ListDomainRequest, opts ...grpc.CallOption) (*DomainsResponse, error) {
	out := new(DomainsResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/ListDomain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) AddDomainResourceRecord(ctx context.Context, in *CreateDomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordResponse, error) {
	out := new(DomainResourceRecordResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/AddDomainResourceRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) UpdateDomainResourceRecord(ctx context.Context, in *UpdateDomainResourceRecordRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/UpdateDomainResourceRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) DeleteDomainResourceRecord(ctx context.Context, in *DomainResourceRecordRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/DeleteDomainResourceRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) GetDomainResourceRecord(ctx context.Context, in *DomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordResponse, error) {
	out := new(DomainResourceRecordResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/GetDomainResourceRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) FindDomainResourceRecord(ctx context.Context, in *FindDomainResourceRecordRequest, opts ...grpc.CallOption) (*DomainResourceRecordsResponse, error) {
	out := new(DomainResourceRecordsResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/FindDomainResourceRecord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) CreateIdentityIdentifier(ctx context.Context, in *CreateIdentityIdentifierRequest, opts ...grpc.CallOption) (*IdentityIdentifierResponse, error) {
	out := new(IdentityIdentifierResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/CreateIdentityIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) DeleteIdentityIdentifier(ctx context.Context, in *IdentityIdentifierRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/DeleteIdentityIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) GetIdentityIdentifier(ctx context.Context, in *IdentityIdentifierRequest, opts ...grpc.CallOption) (*IdentityIdentifierResponse, error) {
	out := new(IdentityIdentifierResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/GetIdentityIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) CreateDataIdentifier(ctx context.Context, in *CreateDataIdentifierRequest, opts ...grpc.CallOption) (*DataIdentifierResponse, error) {
	out := new(DataIdentifierResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/CreateDataIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) DeleteDataIdentifier(ctx context.Context, in *DataIdentifierRequest, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/DeleteDataIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) GetDataIdentifier(ctx context.Context, in *DataIdentifierRequest, opts ...grpc.CallOption) (*DataIdentifierResponse, error) {
	out := new(DataIdentifierResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/GetDataIdentifier", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) GetDataIdentifiers(ctx context.Context, in *GeneralPaginationRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error) {
	out := new(DataIdentifiersResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/GetDataIdentifiers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) FindDataIdentifierByOwner(ctx context.Context, in *FindDataIdentifierByOwnerRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error) {
	out := new(DataIdentifiersResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/FindDataIdentifierByOwner", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) FindDataIdentifierByMetadata(ctx context.Context, in *FindDataIdentifierByMetadataRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error) {
	out := new(DataIdentifiersResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/FindDataIdentifierByMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *entropyServiceClient) FindDataIdentifierByTag(ctx context.Context, in *FindDataIdentifierByTagRequest, opts ...grpc.CallOption) (*DataIdentifiersResponse, error) {
	out := new(DataIdentifiersResponse)
	err := c.cc.Invoke(ctx, "/api.EntropyService/FindDataIdentifierByTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntropyServiceServer is the server API for EntropyService service.
// All implementations must embed UnimplementedEntropyServiceServer
// for forward compatibility
type EntropyServiceServer interface {
	// For TLD, when we using HLF, it seems like the channel in HLF.
	AvailableNamespace(context.Context, *GeneralPaginationRequest) (*NamespacesResponse, error)
	CurrentNamespace(context.Context, *GeneralRequest) (*NamespaceResponse, error)
	ActivateNamespace(context.Context, *NamespaceRequest) (*GeneralResponse, error)
	// For Domain
	CreateDomain(context.Context, *CreateDomainRequest) (*GeneralResponse, error)
	DeleteDomain(context.Context, *DomainRequest) (*GeneralResponse, error)
	GetDomain(context.Context, *DomainRequest) (*DomainResponse, error)
	ListDomain(context.Context, *ListDomainRequest) (*DomainsResponse, error)
	// For DNS RR
	AddDomainResourceRecord(context.Context, *CreateDomainResourceRecordRequest) (*DomainResourceRecordResponse, error)
	UpdateDomainResourceRecord(context.Context, *UpdateDomainResourceRecordRequest) (*GeneralResponse, error)
	DeleteDomainResourceRecord(context.Context, *DomainResourceRecordRequest) (*GeneralResponse, error)
	GetDomainResourceRecord(context.Context, *DomainResourceRecordRequest) (*DomainResourceRecordResponse, error)
	FindDomainResourceRecord(context.Context, *FindDomainResourceRecordRequest) (*DomainResourceRecordsResponse, error)
	// For Identifier
	CreateIdentityIdentifier(context.Context, *CreateIdentityIdentifierRequest) (*IdentityIdentifierResponse, error)
	DeleteIdentityIdentifier(context.Context, *IdentityIdentifierRequest) (*GeneralResponse, error)
	GetIdentityIdentifier(context.Context, *IdentityIdentifierRequest) (*IdentityIdentifierResponse, error)
	// For Data Identifier
	CreateDataIdentifier(context.Context, *CreateDataIdentifierRequest) (*DataIdentifierResponse, error)
	DeleteDataIdentifier(context.Context, *DataIdentifierRequest) (*GeneralResponse, error)
	GetDataIdentifier(context.Context, *DataIdentifierRequest) (*DataIdentifierResponse, error)
	GetDataIdentifiers(context.Context, *GeneralPaginationRequest) (*DataIdentifiersResponse, error)
	FindDataIdentifierByOwner(context.Context, *FindDataIdentifierByOwnerRequest) (*DataIdentifiersResponse, error)
	FindDataIdentifierByMetadata(context.Context, *FindDataIdentifierByMetadataRequest) (*DataIdentifiersResponse, error)
	FindDataIdentifierByTag(context.Context, *FindDataIdentifierByTagRequest) (*DataIdentifiersResponse, error)
	mustEmbedUnimplementedEntropyServiceServer()
}

// UnimplementedEntropyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEntropyServiceServer struct {
}

func (UnimplementedEntropyServiceServer) AvailableNamespace(context.Context, *GeneralPaginationRequest) (*NamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AvailableNamespace not implemented")
}
func (UnimplementedEntropyServiceServer) CurrentNamespace(context.Context, *GeneralRequest) (*NamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CurrentNamespace not implemented")
}
func (UnimplementedEntropyServiceServer) ActivateNamespace(context.Context, *NamespaceRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateNamespace not implemented")
}
func (UnimplementedEntropyServiceServer) CreateDomain(context.Context, *CreateDomainRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDomain not implemented")
}
func (UnimplementedEntropyServiceServer) DeleteDomain(context.Context, *DomainRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomain not implemented")
}
func (UnimplementedEntropyServiceServer) GetDomain(context.Context, *DomainRequest) (*DomainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomain not implemented")
}
func (UnimplementedEntropyServiceServer) ListDomain(context.Context, *ListDomainRequest) (*DomainsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDomain not implemented")
}
func (UnimplementedEntropyServiceServer) AddDomainResourceRecord(context.Context, *CreateDomainResourceRecordRequest) (*DomainResourceRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDomainResourceRecord not implemented")
}
func (UnimplementedEntropyServiceServer) UpdateDomainResourceRecord(context.Context, *UpdateDomainResourceRecordRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDomainResourceRecord not implemented")
}
func (UnimplementedEntropyServiceServer) DeleteDomainResourceRecord(context.Context, *DomainResourceRecordRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDomainResourceRecord not implemented")
}
func (UnimplementedEntropyServiceServer) GetDomainResourceRecord(context.Context, *DomainResourceRecordRequest) (*DomainResourceRecordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDomainResourceRecord not implemented")
}
func (UnimplementedEntropyServiceServer) FindDomainResourceRecord(context.Context, *FindDomainResourceRecordRequest) (*DomainResourceRecordsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDomainResourceRecord not implemented")
}
func (UnimplementedEntropyServiceServer) CreateIdentityIdentifier(context.Context, *CreateIdentityIdentifierRequest) (*IdentityIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIdentityIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) DeleteIdentityIdentifier(context.Context, *IdentityIdentifierRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIdentityIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) GetIdentityIdentifier(context.Context, *IdentityIdentifierRequest) (*IdentityIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIdentityIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) CreateDataIdentifier(context.Context, *CreateDataIdentifierRequest) (*DataIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDataIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) DeleteDataIdentifier(context.Context, *DataIdentifierRequest) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDataIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) GetDataIdentifier(context.Context, *DataIdentifierRequest) (*DataIdentifierResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataIdentifier not implemented")
}
func (UnimplementedEntropyServiceServer) GetDataIdentifiers(context.Context, *GeneralPaginationRequest) (*DataIdentifiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataIdentifiers not implemented")
}
func (UnimplementedEntropyServiceServer) FindDataIdentifierByOwner(context.Context, *FindDataIdentifierByOwnerRequest) (*DataIdentifiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataIdentifierByOwner not implemented")
}
func (UnimplementedEntropyServiceServer) FindDataIdentifierByMetadata(context.Context, *FindDataIdentifierByMetadataRequest) (*DataIdentifiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataIdentifierByMetadata not implemented")
}
func (UnimplementedEntropyServiceServer) FindDataIdentifierByTag(context.Context, *FindDataIdentifierByTagRequest) (*DataIdentifiersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindDataIdentifierByTag not implemented")
}
func (UnimplementedEntropyServiceServer) mustEmbedUnimplementedEntropyServiceServer() {}

// UnsafeEntropyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EntropyServiceServer will
// result in compilation errors.
type UnsafeEntropyServiceServer interface {
	mustEmbedUnimplementedEntropyServiceServer()
}

func RegisterEntropyServiceServer(s grpc.ServiceRegistrar, srv EntropyServiceServer) {
	s.RegisterService(&EntropyService_ServiceDesc, srv)
}

func _EntropyService_AvailableNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).AvailableNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/AvailableNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).AvailableNamespace(ctx, req.(*GeneralPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_CurrentNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).CurrentNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/CurrentNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).CurrentNamespace(ctx, req.(*GeneralRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_ActivateNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).ActivateNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/ActivateNamespace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).ActivateNamespace(ctx, req.(*NamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_CreateDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).CreateDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/CreateDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).CreateDomain(ctx, req.(*CreateDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_DeleteDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).DeleteDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/DeleteDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).DeleteDomain(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_GetDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).GetDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/GetDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).GetDomain(ctx, req.(*DomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_ListDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDomainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).ListDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/ListDomain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).ListDomain(ctx, req.(*ListDomainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_AddDomainResourceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDomainResourceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).AddDomainResourceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/AddDomainResourceRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).AddDomainResourceRecord(ctx, req.(*CreateDomainResourceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_UpdateDomainResourceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDomainResourceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).UpdateDomainResourceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/UpdateDomainResourceRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).UpdateDomainResourceRecord(ctx, req.(*UpdateDomainResourceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_DeleteDomainResourceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainResourceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).DeleteDomainResourceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/DeleteDomainResourceRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).DeleteDomainResourceRecord(ctx, req.(*DomainResourceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_GetDomainResourceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainResourceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).GetDomainResourceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/GetDomainResourceRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).GetDomainResourceRecord(ctx, req.(*DomainResourceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_FindDomainResourceRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDomainResourceRecordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).FindDomainResourceRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/FindDomainResourceRecord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).FindDomainResourceRecord(ctx, req.(*FindDomainResourceRecordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_CreateIdentityIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIdentityIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).CreateIdentityIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/CreateIdentityIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).CreateIdentityIdentifier(ctx, req.(*CreateIdentityIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_DeleteIdentityIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).DeleteIdentityIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/DeleteIdentityIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).DeleteIdentityIdentifier(ctx, req.(*IdentityIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_GetIdentityIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentityIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).GetIdentityIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/GetIdentityIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).GetIdentityIdentifier(ctx, req.(*IdentityIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_CreateDataIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).CreateDataIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/CreateDataIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).CreateDataIdentifier(ctx, req.(*CreateDataIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_DeleteDataIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).DeleteDataIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/DeleteDataIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).DeleteDataIdentifier(ctx, req.(*DataIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_GetDataIdentifier_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DataIdentifierRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).GetDataIdentifier(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/GetDataIdentifier",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).GetDataIdentifier(ctx, req.(*DataIdentifierRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_GetDataIdentifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneralPaginationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).GetDataIdentifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/GetDataIdentifiers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).GetDataIdentifiers(ctx, req.(*GeneralPaginationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_FindDataIdentifierByOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDataIdentifierByOwnerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).FindDataIdentifierByOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/FindDataIdentifierByOwner",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).FindDataIdentifierByOwner(ctx, req.(*FindDataIdentifierByOwnerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_FindDataIdentifierByMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDataIdentifierByMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).FindDataIdentifierByMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/FindDataIdentifierByMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).FindDataIdentifierByMetadata(ctx, req.(*FindDataIdentifierByMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EntropyService_FindDataIdentifierByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindDataIdentifierByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntropyServiceServer).FindDataIdentifierByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EntropyService/FindDataIdentifierByTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntropyServiceServer).FindDataIdentifierByTag(ctx, req.(*FindDataIdentifierByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EntropyService_ServiceDesc is the grpc.ServiceDesc for EntropyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EntropyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.EntropyService",
	HandlerType: (*EntropyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AvailableNamespace",
			Handler:    _EntropyService_AvailableNamespace_Handler,
		},
		{
			MethodName: "CurrentNamespace",
			Handler:    _EntropyService_CurrentNamespace_Handler,
		},
		{
			MethodName: "ActivateNamespace",
			Handler:    _EntropyService_ActivateNamespace_Handler,
		},
		{
			MethodName: "CreateDomain",
			Handler:    _EntropyService_CreateDomain_Handler,
		},
		{
			MethodName: "DeleteDomain",
			Handler:    _EntropyService_DeleteDomain_Handler,
		},
		{
			MethodName: "GetDomain",
			Handler:    _EntropyService_GetDomain_Handler,
		},
		{
			MethodName: "ListDomain",
			Handler:    _EntropyService_ListDomain_Handler,
		},
		{
			MethodName: "AddDomainResourceRecord",
			Handler:    _EntropyService_AddDomainResourceRecord_Handler,
		},
		{
			MethodName: "UpdateDomainResourceRecord",
			Handler:    _EntropyService_UpdateDomainResourceRecord_Handler,
		},
		{
			MethodName: "DeleteDomainResourceRecord",
			Handler:    _EntropyService_DeleteDomainResourceRecord_Handler,
		},
		{
			MethodName: "GetDomainResourceRecord",
			Handler:    _EntropyService_GetDomainResourceRecord_Handler,
		},
		{
			MethodName: "FindDomainResourceRecord",
			Handler:    _EntropyService_FindDomainResourceRecord_Handler,
		},
		{
			MethodName: "CreateIdentityIdentifier",
			Handler:    _EntropyService_CreateIdentityIdentifier_Handler,
		},
		{
			MethodName: "DeleteIdentityIdentifier",
			Handler:    _EntropyService_DeleteIdentityIdentifier_Handler,
		},
		{
			MethodName: "GetIdentityIdentifier",
			Handler:    _EntropyService_GetIdentityIdentifier_Handler,
		},
		{
			MethodName: "CreateDataIdentifier",
			Handler:    _EntropyService_CreateDataIdentifier_Handler,
		},
		{
			MethodName: "DeleteDataIdentifier",
			Handler:    _EntropyService_DeleteDataIdentifier_Handler,
		},
		{
			MethodName: "GetDataIdentifier",
			Handler:    _EntropyService_GetDataIdentifier_Handler,
		},
		{
			MethodName: "GetDataIdentifiers",
			Handler:    _EntropyService_GetDataIdentifiers_Handler,
		},
		{
			MethodName: "FindDataIdentifierByOwner",
			Handler:    _EntropyService_FindDataIdentifierByOwner_Handler,
		},
		{
			MethodName: "FindDataIdentifierByMetadata",
			Handler:    _EntropyService_FindDataIdentifierByMetadata_Handler,
		},
		{
			MethodName: "FindDataIdentifierByTag",
			Handler:    _EntropyService_FindDataIdentifierByTag_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magnolia.proto",
}

// TrustedLedgerServiceClient is the client API for TrustedLedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrustedLedgerServiceClient interface {
	Track(ctx context.Context, in *Event, opts ...grpc.CallOption) (*GeneralResponse, error)
	Trace(ctx context.Context, in *TracingRequest, opts ...grpc.CallOption) (*TracingResponse, error)
}

type trustedLedgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrustedLedgerServiceClient(cc grpc.ClientConnInterface) TrustedLedgerServiceClient {
	return &trustedLedgerServiceClient{cc}
}

func (c *trustedLedgerServiceClient) Track(ctx context.Context, in *Event, opts ...grpc.CallOption) (*GeneralResponse, error) {
	out := new(GeneralResponse)
	err := c.cc.Invoke(ctx, "/api.TrustedLedgerService/Track", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trustedLedgerServiceClient) Trace(ctx context.Context, in *TracingRequest, opts ...grpc.CallOption) (*TracingResponse, error) {
	out := new(TracingResponse)
	err := c.cc.Invoke(ctx, "/api.TrustedLedgerService/Trace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrustedLedgerServiceServer is the server API for TrustedLedgerService service.
// All implementations must embed UnimplementedTrustedLedgerServiceServer
// for forward compatibility
type TrustedLedgerServiceServer interface {
	Track(context.Context, *Event) (*GeneralResponse, error)
	Trace(context.Context, *TracingRequest) (*TracingResponse, error)
	mustEmbedUnimplementedTrustedLedgerServiceServer()
}

// UnimplementedTrustedLedgerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrustedLedgerServiceServer struct {
}

func (UnimplementedTrustedLedgerServiceServer) Track(context.Context, *Event) (*GeneralResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Track not implemented")
}
func (UnimplementedTrustedLedgerServiceServer) Trace(context.Context, *TracingRequest) (*TracingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Trace not implemented")
}
func (UnimplementedTrustedLedgerServiceServer) mustEmbedUnimplementedTrustedLedgerServiceServer() {}

// UnsafeTrustedLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrustedLedgerServiceServer will
// result in compilation errors.
type UnsafeTrustedLedgerServiceServer interface {
	mustEmbedUnimplementedTrustedLedgerServiceServer()
}

func RegisterTrustedLedgerServiceServer(s grpc.ServiceRegistrar, srv TrustedLedgerServiceServer) {
	s.RegisterService(&TrustedLedgerService_ServiceDesc, srv)
}

func _TrustedLedgerService_Track_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustedLedgerServiceServer).Track(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TrustedLedgerService/Track",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustedLedgerServiceServer).Track(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrustedLedgerService_Trace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TracingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrustedLedgerServiceServer).Trace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.TrustedLedgerService/Trace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrustedLedgerServiceServer).Trace(ctx, req.(*TracingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrustedLedgerService_ServiceDesc is the grpc.ServiceDesc for TrustedLedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrustedLedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.TrustedLedgerService",
	HandlerType: (*TrustedLedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Track",
			Handler:    _TrustedLedgerService_Track_Handler,
		},
		{
			MethodName: "Trace",
			Handler:    _TrustedLedgerService_Trace_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magnolia.proto",
}
